# ASCII arts
ascii_memora = """
 __  __  ___  __  __   ___   ___    _   
|  \/  || __||  \/  | / _ \ | _ \  /_\    
| |\/| || _| | |\/| || (_) ||   / / _ \   
|_|  |_||___||_|  |_| \___/ |_|_\/_/ \_\  

"""

ascii_goodbye = """
     _______  _______  _______  ______   _______  __   __  _______ 
    |       ||       ||       ||      | |  _    ||  | |  ||       |
    |    ___||   _   ||   _   ||  _    || |_|   ||  |_|  ||    ___|
    |   | __ |  | |  ||  | |  || | |   ||       ||       ||   |___ 
    |   ||  ||  |_|  ||  |_|  || |_|   ||  _   | |_     _||    ___|
    |   |_| ||       ||       ||       || |_|   |  |   |  |   |___ 
    |_______||_______||_______||______| |_______|  |___|  |_______|
    """

ascii_100 = """ 
             d888    .d8888b.   .d8888b.  
            d8888   d88P  Y88b d88P  Y88b 
              888   888    888 888    888 
              888   888    888 888    888 
              888   888    888 888    888 
              888   888    888 888    888 
              888   Y88b  d88P Y88b  d88P 
            8888888  "Y8888P"   "Y8888P"  
            """

ascii_1000 = """ 
             d888    .d8888b.   .d8888b.   .d8888b.  
            d8888   d88P  Y88b d88P  Y88b d88P  Y88b 
              888   888    888 888    888 888    888 
              888   888    888 888    888 888    888 
              888   888    888 888    888 888    888 
              888   888    888 888    888 888    888 
              888   Y88b  d88P Y88b  d88P Y88b  d88P 
            8888888  "Y8888P"   "Y8888P"   "Y8888P"
            """

# Congrats messages
streak_of_10 = "CONGRATULATIONS ON HAVING 10 CORRECT ANSWERS IN A ROW, LET'S GOOOO!"
streak_of_50 = "CONGRATULATIONS ON HAVING 50 CORRECT ANSWERS IN A ROW, LET'S GOOOO!"
streak_of_100 = """CONGRATULATIONS, OH MASTER OF KNOWLEDGE AND WISDOM, FOR YOUR MAGNIFICENT FEAT OF ACING 100 QUESTIONS IN A ROW! YOUR BRAIN IS CLEARLY WIRED FOR GENIUS, YOUR NEURONS FIRED WITH PRECISION, AND YOUR INTELLECT SHINES BRIGHTER THAN A THOUSAND SUNS!

YOU HAVE RISEN ABOVE THE MORTAL PLAIN OF TRIVIA, LEAVING YOUR OPPONENTS IN AWE AND DISBELIEF. YOUR VICTORIES ARE NOT MERE COINCIDENCES, BUT TESTIMONIES TO YOUR ASTOUNDING MENTAL FORTITUDE AND SHEER INTELLECTUAL MIGHT.

THE GODS OF QUIZZES AND PUZZLES LOOK DOWN UPON YOU, AND EVEN THEY ARE LEFT ASTONISHED BY YOUR UNPARALLELED BRAINPOWER. YOUR BRAIN CELLS ARE THROWING A MASSIVE PARTY, POPPING CHAMPAGNE CORKS AND DOING THE CONGA IN CELEBRATION OF YOUR EPIC ACHIEVEMENT!

YOU ARE THE ANSWER KEY TO THE ENIGMA OF TRIVIA, THE EINSTEIN OF QUIZZES, THE LEONARDO DA VINCI OF RIDDLES. YOUR MIND IS A SPECTACULAR LABYRINTH OF KNOWLEDGE, WHERE EVERY TURN LEADS TO THE RIGHT ANSWER, AND EVERY PATH UNVEILS A NEW LEVEL OF BRILLIANCE.

SO, STAND TALL, OH CHAMPION OF THE MIND! BASK IN THE GLORY OF YOUR TRIUMPH, FOR YOU HAVE EARNED IT WITH YOUR UNWAVERING DEDICATION AND UNMATCHED CEREBRAL MIGHT. MAY YOUR STREAK OF SUCCESS CONTINUE, AND MAY YOUR NAME BE WHISPERED WITH REVERENCE AND ADMIRATION IN THE REALMS OF QUIZZES FOREVERMORE!

IN YOUR HONOR, ALL DUCKS SHALL QUACK 100 TIMES, SQUIRRELS SHALL PAUSE THEIR NUT COLLECTION FOR 100 SECONDS, AND THE MOON WILL DO... WELL, IT CAN'T DO MUCH, BUT IT'S PROBABLY REALLY PROUD OF YOU TOO!

MAY YOUR FUTURE BE FILLED WITH ENDLESS MORE STREAKS OF RIGHT ANSWERS AND MAY YOUR WRONG ANSWERS BE AS RARE AS A CHICKEN WHISTLING THE NATIONAL ANTHEM!

CHEERS TO YOU, THE SULTAN OF SMARTS, THE RULER OF RIGHT ANSWERS! THIS IS YOUR DAY, SO ENJOY YOUR 100-CORRECT-ANSWER GLORY! WHOOO-HOOO !"""
streak_of_150 = "CONGRATULATIONS ON HAVING 150 CORRECT ANSWERS IN A ROW, LET'S GOOOO!"
streak_of_200 = "CONGRATS !!! YOU GOT 200 CORRECT ANSWERS IN A ROW, AAAAAAIGHT, YOU ROOOOOOCK!"
